---
- name: Update packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install MariaDB server and dependencies
  ansible.builtin.package:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: latest

- name: Check MariaDB is running and enabled
  ansible.builtin.service:
    name: mariadb.service
    state: started
    enabled: true

- name: Allow MySQL connections through firewall
  ansible.builtin.firewalld:
    service: mysql
    permanent: yes
    zone: public
    state: enabled
  notify:
    - Reload firewalld

- include: mariadb_hardening.yml

- name: Create Wordpress database
  community.mysql.mysql_db:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: wordpress_db
    state: present

- name: Create new user for Wordpress database
  community.mysql.mysql_user:
    login_host: localhost
    login_user: root
    # login_unix_socket: /var/run/mysqld/mysqld.sock
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    host: "%"
    priv: 'wordpress_db.*:ALL,GRANT'
    state: present
