---
- name: Delete anonymous MySQL users
  community.mysql.mysql_user:
    name: ""
    state: absent

- name: Remove 'test' database
  community.mysql.mysql_db:
    name: test
    state: absent

- name: Set root password
  community.mysql.mysql_user:
    login_host: localhost
    login_user: root
    login_password: ""
    name: root
    password: "{{ mysql_root_password }}"

#- name: Remove remote root access
#  community.mysql.mysql_user:
#    check_implicit_admin: true
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    user: root
#    host: "{{ ansible_hostname }}"
#    state: absent