---
- name: Reload firewalld
  service:
    name: firewalld
    state: restarted

- name: Restart haproxy
  service:
    name: haproxy
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted